const fs=require('fs'),ROOT='/workspaces/lx-music-mobile'
function patch(f,s,r,d){const p=ROOT+'/'+f;let c=fs.readFileSync(p,'utf-8');if(c.includes(r)){console.log('✅ '+f+' 已修改 ('+d+')');return}if(!c.includes(s)){console.log('❌ '+f+' 未匹配 ('+d+')');return}fs.writeFileSync(p,c.replace(s,r),'utf-8');console.log('✅ '+f+' 修改成功 ('+d+')')}
patch('src/screens/Home/Horizontal/Aside.tsx',"const uri = file.path.startsWith('file://') ? file.path : 'file://' + file.path","const uri = WALLPAPER_FILE.startsWith('file://') ? WALLPAPER_FILE : 'file://' + WALLPAPER_FILE",'修复壁纸路径');
patch('src/screens/Home/Horizontal/Aside.tsx',"// toPath模式下文件被复制到目标路径，使用path属性\n      ","// toPath模式：文件已复制到WALLPAPER_FILE\n      ",'修复壁纸注释');
patch('src/components/PageContent.tsx',"source={{ uri: wallpaperUri, headers: defaultHeaders }}\n              resizeMode=\"cover\"\n              blurRadius={BLUR_RADIUS}\n            >\n              <View style={{ flex: 1, backgroundColor: 'rgba(6, 10, 30, 0.18)' }} />\n            </ImageBackground>","source={{ uri: wallpaperUri }}\n              resizeMode=\"cover\"\n              blurRadius={BLUR_RADIUS}\n            >\n              <View style={{ flex: 1, backgroundColor: 'rgba(6, 10, 30, 0.18)' }} />\n            </ImageBackground>",'去除headers(玻璃)');
patch('src/components/PageContent.tsx',"source={{ uri: wallpaperUri, headers: defaultHeaders }}\n            resizeMode=\"cover\"\n            blurRadius={BLUR_RADIUS}\n          >\n            {/* 暗化遮罩 */}\n            <View style={{ flex: 1, backgroundColor: theme['c-content-background'], opacity: 0.55 }} />","source={{ uri: wallpaperUri }}\n            resizeMode=\"cover\"\n            blurRadius={BLUR_RADIUS}\n          >\n            <View style={{ flex: 1, backgroundColor: theme['c-content-background'], opacity: 0.55 }} />",'去除headers(非玻璃)');
patch('src/core/init/index.ts',"import { checkUpdate } from '@/core/version'\nimport { bootLog } from '@/utils/bootLog'\nimport { cheatTip } from '@/utils/tools'","import { bootLog } from '@/utils/bootLog'",'清理import');
patch('src/core/init/index.ts',"  await cheatTip()\n  if (settingState.setting['common.isAgreePact']) {\n    if (isFirstPush) {\n      isFirstPush = false\n      void checkUpdate()\n      void initDeeplink()\n    }\n  } else {\n    if (isFirstPush) isFirstPush = false\n    showPactModal()\n  }","  if (settingState.setting['common.isAgreePact']) {\n    if (isFirstPush) {\n      isFirstPush = false\n      void initDeeplink()\n    }\n  } else {\n    if (isFirstPush) isFirstPush = false\n    commonActions.updateSetting({ 'common.isAgreePact': true })\n  }",'去掉启动提示');
console.log('\n修复完成!')
