//! 更新默认主题配置后，需要执行 npm run build:theme 重新构建index.json

const fs = require('fs')
const path = require('path')
const { createThemeColors } = require('./utils')

const defaultThemes = [
  {
    id: 'green',
    name: '绿意盎然',
    isDark: false,
    config: {
      primary: 'rgb(77, 175, 124)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#4baed5',
      'c-badge-tertiary': '#e7aa36',
    },
  },
  {
    id: 'blue',
    name: '蓝田生玉',
    isDark: false,
    config: {
      primary: 'rgb(52, 152, 219)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#5cbf9b',
      'c-badge-tertiary': '#5cbf9b',
    },
  },
  {
    id: 'blue_plus',
    name: '蛋雅深蓝',
    isDark: false,
    config: {
      primary: 'rgb(77, 131, 175)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-600)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': 'rgba(66.6, 150.7, 171, 1)',
      'c-badge-tertiary': 'rgba(54, 196, 231, 1)',
    },
  },
  {
    id: 'orange',
    name: '橙黄橘绿',
    isDark: false,
    config: {
      primary: 'rgb(245, 171, 53)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#9ed458',
      'c-badge-tertiary': '#9ed458',
    },
  },
  {
    id: 'brown',
    name: '泥牛入海',
    isDark: false,
    config: {
      primary: 'rgba(188, 128, 68, 1)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#483472',
      'c-badge-tertiary': '#647D39',
    },
  },
  {
    id: 'red',
    name: '热情似火',
    isDark: false,
    config: {
      primary: 'rgb(214, 69, 65)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#dfbb6b',
      'c-badge-tertiary': '#dfbb6b',
    },
  },
  {
    id: 'pink',
    name: '粉装玉琢',
    isDark: false,
    config: {
      primary: 'rgb(241, 130, 141)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#f5b684',
      'c-badge-tertiary': '#f5b684',
    },
  },
  {
    id: 'purple',
    name: '重斤球紫',
    isDark: false,
    config: {
      primary: 'rgb(155, 89, 182)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#e5a39f',
      'c-badge-tertiary': '#e5a39f',
    },
  },
  {
    id: 'grey',
    name: '灰常美丽',
    isDark: false,
    config: {
      primary: 'rgb(108, 122, 137)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#b19b9f',
      'c-badge-tertiary': '#b19b9f',
    },
  },
  {
    id: 'ming',
    name: '青出于黑',
    isDark: false,
    config: {
      primary: 'rgb(51, 110, 123)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#6376a2',
      'c-badge-tertiary': '#6376a2',
    },
  },
  {
    id: 'blue2',
    name: '清热板蓝',
    isDark: false,
    config: {
      primary: 'rgb(79, 98, 208)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'var(c-primary-light-600-alpha-700)',
      'c-main-background': 'rgba(255, 255, 255, 1)',
      'bg-image': '',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#b080db',
      'c-badge-tertiary': '#b080db',
    },
  },
  {
    id: 'black',
    name: '黑灯瞎火',
    isDark: true,
    config: {
      primary: 'rgb(190, 190, 190)',
      font: 'rgb(255, 255, 255)',
      'c-app-background': 'rgba(0, 0, 0, 0)',
      'c-main-background': 'rgba(19, 19, 19, 0.95)',
      'bg-image': 'landingMoon.png',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary-dark-200)',
      'c-badge-secondary': 'var(c-primary)',
      'c-badge-tertiary': 'var(c-primary-dark-300)',
    },
  },
  {
    id: 'mid_autumn',
    name: '月里嫦娥',
    isDark: false,
    config: {
      primary: 'rgb(74, 55, 82)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'rgba(255, 255, 255, 0)',
      'c-main-background': 'rgba(255, 255, 255, 0.9)',
      'bg-image': 'jqbg.jpg',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',


      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': '#af9479',
      'c-badge-tertiary': '#af9479',
    },
  },
  {
    id: 'naruto',
    name: '木叶之村',
    isDark: false,
    config: {
      primary: 'rgb(87, 144, 167)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'rgba(255, 255, 255, 0.15)',
      'c-main-background': 'rgba(255, 255, 255, 0.8)',
      'bg-image': 'myzcbg.jpg',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': 'var(c-primary)',
      'c-badge-secondary': 'var(c-primary-light-100)',
      'c-badge-tertiary': 'var(c-primary-light-100)',
    },
  },
  {
    id: 'china_ink',
    name: '近墨者黑',
    isDark: false,
    config: {
      primary: 'rgba(47, 47, 47, 1)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'rgba(255, 255, 255, 0)',
      'c-main-background': 'rgba(255, 255, 255, 0.8)',
      'bg-image': 'china_ink.jpg',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',


      'c-badge-primary': 'rgba(137, 70, 70, 1)',
      'c-badge-secondary': 'rgba(67, 139, 65, 1)',
      'c-badge-tertiary': 'rgba(132, 135, 65, 1)',
    },
  },
  {
    id: 'happy_new_year',
    name: '新年快乐',
    isDark: false,
    config: {
      primary: 'rgb(192, 57, 43)',
      font: 'rgb(33, 33, 33)',
      'c-app-background': 'rgba(255, 255, 255, 0.15)',
      'c-main-background': 'rgba(255, 255, 255, 0.8)',
      'bg-image': 'xnkl.png',
      'bg-image-position': 'center',
      'bg-image-size': 'cover',

      'c-badge-primary': '#7fb575',
      'c-badge-secondary': '#dfbb6b',
      'c-badge-tertiary': 'var(c-primary-light-100)',
    },
  },,
  },
  },
  },
  },
  },
  },
,
  {
    id: 'glass_cosmos', name: '深空星河', isDark: true,
    config: {
      primary: 'rgb(100, 160, 255)', font: 'rgb(210, 220, 255)',
      'c-app-background': 'rgba(6, 10, 30, 0)', 'c-main-background': 'rgba(10, 16, 40, 0.45)',
      'c-content-background': 'rgba(14, 20, 50, 0.50)', 'c-border-background': 'rgba(100, 160, 255, 0.12)',
      'bg-image': '', 'bg-image-position': 'center', 'bg-image-size': 'cover',
      'c-badge-primary': 'rgb(100, 160, 255)', 'c-badge-secondary': 'rgb(150, 100, 255)', 'c-badge-tertiary': 'rgb(200, 200, 255)',
    },
  },
  {
    id: 'glass_amber', name: '琥珀辉光', isDark: true,
    config: {
      primary: 'rgb(255, 175, 50)', font: 'rgb(240, 225, 200)',
      'c-app-background': 'rgba(26, 14, 2, 0)', 'c-main-background': 'rgba(40, 25, 8, 0.40)',
      'c-content-background': 'rgba(50, 32, 10, 0.40)', 'c-border-background': 'rgba(255, 175, 50, 0.12)',
      'bg-image': '', 'bg-image-position': 'center', 'bg-image-size': 'cover',
      'c-badge-primary': 'rgb(255, 175, 50)', 'c-badge-secondary': 'rgb(255, 120, 50)', 'c-badge-tertiary': 'rgb(255, 220, 100)',
    },
  },
  {
    id: 'glass_emerald', name: '翡翠薄雾', isDark: true,
    config: {
      primary: 'rgb(16, 185, 129)', font: 'rgb(200, 240, 220)',
      'c-app-background': 'rgba(2, 20, 10, 0)', 'c-main-background': 'rgba(5, 30, 20, 0.40)',
      'c-content-background': 'rgba(8, 38, 26, 0.40)', 'c-border-background': 'rgba(16, 185, 129, 0.12)',
      'bg-image': '', 'bg-image-position': 'center', 'bg-image-size': 'cover',
      'c-badge-primary': 'rgb(16, 185, 129)', 'c-badge-secondary': 'rgb(50, 210, 160)', 'c-badge-tertiary': 'rgb(110, 231, 183)',
    },
  },
  {
    id: 'glass_crimson', name: '绯红帷幕', isDark: true,
    config: {
      primary: 'rgb(220, 60, 60)', font: 'rgb(240, 200, 200)',
      'c-app-background': 'rgba(25, 5, 5, 0)', 'c-main-background': 'rgba(35, 10, 10, 0.40)',
      'c-content-background': 'rgba(45, 14, 14, 0.40)', 'c-border-background': 'rgba(220, 60, 60, 0.12)',
      'bg-image': '', 'bg-image-position': 'center', 'bg-image-size': 'cover',
      'c-badge-primary': 'rgb(220, 60, 60)', 'c-badge-secondary': 'rgb(255, 120, 80)', 'c-badge-tertiary': 'rgb(255, 150, 150)',
    },
  },
  {
    id: 'glass_violet', name: '紫罗兰星云', isDark: true,
    config: {
      primary: 'rgb(160, 90, 255)', font: 'rgb(225, 210, 255)',
      'c-app-background': 'rgba(15, 5, 25, 0)', 'c-main-background': 'rgba(22, 10, 35, 0.40)',
      'c-content-background': 'rgba(28, 14, 45, 0.40)', 'c-border-background': 'rgba(160, 90, 255, 0.12)',
      'bg-image': '', 'bg-image-position': 'center', 'bg-image-size': 'cover',
      'c-badge-primary': 'rgb(160, 90, 255)', 'c-badge-secondary': 'rgb(200, 120, 255)', 'c-badge-tertiary': 'rgb(120, 180, 255)',
    },
  },
  {
    id: 'glass_arctic', name: '极地霜华', isDark: true,
    config: {
      primary: 'rgb(80, 210, 255)', font: 'rgb(210, 235, 255)',
      'c-app-background': 'rgba(3, 12, 22, 0)', 'c-main-background': 'rgba(5, 18, 30, 0.40)',
      'c-content-background': 'rgba(8, 22, 38, 0.40)', 'c-border-background': 'rgba(80, 210, 255, 0.12)',
      'bg-image': '', 'bg-image-position': 'center', 'bg-image-size': 'cover',
      'c-badge-primary': 'rgb(80, 210, 255)', 'c-badge-secondary': 'rgb(140, 230, 255)', 'c-badge-tertiary': 'rgb(180, 240, 255)',
    },
  },

]